// Generated by Haxe 3.4.4

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.lang {
	public class DceNo : global::haxe.lang.HxObject {
		
		public DceNo(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public DceNo() {
			global::haxe.lang.DceNo.__hx_ctor_haxe_lang_DceNo(this);
		}
		
		
		public static void __hx_ctor_haxe_lang_DceNo(global::haxe.lang.DceNo __hx_this) {
		}
		
		
	}
}


